[package]
name = "tiny-tsdb"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1"
nom = "7"
rocksdb = { version = "0.17.0", default-features = false, features = ["zstd"] }
rustyline = "9"